var data = {
  imgClass: "img-fluid",
  products: [
    {
      id: "429",
      name: "Noken",
      description: "Noken adalah Tas tradisional papua, noken sangat multi fungsi bisa isi apa saja dan noken juga memiliki ukuran yang berbedah-bedah",
      price: "50",
      image_title: "Noken",
      image: "https://media.istockphoto.com/id/872250376/id/foto/noken-dari-papua.jpg?s=612x612&w=0&k=20&c=i0PIqPbLOaqdyjwpPEZ-8fSTVeA7ri8V7CuX7KRVoSs=",
    },
    {
      id: "431",
      name: "Gelang",
      description: "Gelang  tradisional papua, gelang ini sangat unik karena dibuat dengan bahan yang alami dari tali tumbuh-tumbuhan",
      price: "30",
      image_title: "Gelang Tangan",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Gelang_Anyaman.jpg/220px-Gelang_Anyaman.jpg",
    },
    {
      id: "432",
      name: "Kalung",
      description: "Kalung  tradisional papua, kalung ini sangat unik karena dibuat dengan bahan yang alami dari tali tumbuh-tumbuhan",
      price: "20",
      image_title: "Kalung",
      image: "https://images.tokopedia.net/img/cache/250-square/VqbcmM/2022/2/15/b93299e1-4f30-4378-96be-1c6acbc92ecd.png?ect=4g",
    },
    {
      id: "433",
      name: "Noken",
      description: "Noken adalah Tas tradisional papua, noken sangat multi fungsi bisa isi apa saja dan noken juga memiliki ukuran yang berbedah-bedah",
      price: "50",
      image_title: "Noken",
      image: "https://i.pinimg.com/736x/7b/bd/22/7bbd221c32886fc53165841acd986296.jpg",
    },
    {
      id: "434",
      name: "Gelang",
      description: "Gelang  tradisional papua, gelang ini sangat unik karena dibuat dengan bahan yang alami dari tali tumbuh-tumbuhan",
      price: "40",
      image_title: "Gelang Tangan",
      image: "https://awsimages.detik.net.id/community/media/visual/2018/01/03/8c977201-6823-4e85-b6ff-ddf1ddf05375_169.jpg?w=620",
    },
    {
      id: "435",
      name: "Kalung",
      description: "Kalung  tradisional papua, kalung ini sangat unik karena dibuat dengan bahan yang alami dari tali tumbuh-tumbuhan",
      price: "20",
      image_title: "Kalung",
      image: "https://s1.bukalapak.com/img/136392982/large/KALUNG_TARING_BABI_HUTAN_PAPUA.jpg",
    },
    {
      id: "433",
      name: "Noken",
      description: "Noken adalah Tas tradisional papua, noken sangat multi fungsi bisa isi apa saja dan noken juga memiliki ukuran yang berbedah-bedah",
      price: "100",
      image_title: "Noken",
      image: "https://wisatanews.id/wp-content/uploads/2021/10/25ab6e5d-b56c-4c3a-8299-ea151a4c84a6.jpeg",
    },
    {
      id: "434",
      name: "Gelang",
      description: "Gelang  tradisional papua, gelang ini sangat unik karena dibuat dengan bahan yang alami dari tali tumbuh-tumbuhan",
      price: "10",
      image_title: "Gelang Tangan",
      image: "https://id-live-01.slatic.net/p/bc605057a5798b4a0b436502039bc7a9.jpg",
    },
    {
      id: "435",
      name: "Kalung",
      description: "Kalung  tradisional papua, kalung ini sangat unik karena dibuat dengan bahan yang alami dari tali tumbuh-tumbuhan",
      price: "60",
      image_title: "Kalung",
      image: "https://images.tokopedia.net/img/cache/250-square/VqbcmM/2022/2/15/b93299e1-4f30-4378-96be-1c6acbc92ecd.png?ect=4g",
    },
    {
      id: "429",
      name: "Noken",
      description: "Noken adalah Tas tradisional papua, noken sangat multi fungsi bisa isi apa saja dan noken juga memiliki ukuran yang berbedah-bedah",
      price: "9.30",
      image_title: "Noken",
      image: "https://cdn.kibrispdr.org/data/467/gambar-noken-papua-10.jpg",
    },
    {
      id: "431",
      name: "Gelang",
      description: "Gelang  tradisional papua, gelang ini sangat unik karena dibuat dengan bahan yang alami dari tali tumbuh-tumbuhan",
      price: "50",
      image_title: "Gelang Tangan",
      image: "https://s4.bukalapak.com/img/4890644303/large/FB_IMG_1533851682693_scaled.jpg",
    },
    {
      id: "432",
      name: "Kalung",
      description: "Kalung  tradisional papua, kalung ini sangat unik karena dibuat dengan bahan yang alami dari tali tumbuh-tumbuhan",
      price: "10.55",
      image_title: "Kalung",
      image: "https://images.tokopedia.net/img/cache/250-square/VqbcmM/2022/2/15/b93299e1-4f30-4378-96be-1c6acbc92ecd.png?ect=4g",
    },
    {
      id: "433",
      name: "Noken",
      description: "Noken adalah Tas tradisional papua, noken sangat multi fungsi bisa isi apa saja dan noken juga memiliki ukuran yang berbedah-bedah",
      price: "500",
      image_title: "Noken",
      image: "https://thumbs.dreamstime.com/b/noken-bag-words-papua-knitted-papuan-women-277693074.jpg",
    },
    {
      id: "434",
      name: "Gelang",
      description: "Gelang  tradisional papua, gelang ini sangat unik karena dibuat dengan bahan yang alami dari tali tumbuh-tumbuhan",
      price: "20.22",
      image_title: "Gelang Tangan",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Gelang_Anyaman.jpg/220px-Gelang_Anyaman.jpg",
    },
    {
      id: "435",
      name: "Kalung",
      description: "Kalung  tradisional papua, kalung ini sangat unik karena dibuat dengan bahan yang alami dari tali tumbuh-tumbuhan",
      price: "5.33",
      image_title: "Kalung",
      image: "https://images.tokopedia.net/img/cache/250-square/VqbcmM/2022/2/15/b93299e1-4f30-4378-96be-1c6acbc92ecd.png?ect=4g",
    },
    {
      id: "433",
      name: "Noken",
      description: "Noken adalah Tas tradisional papua, noken sangat multi fungsi bisa isi apa saja dan noken juga memiliki ukuran yang berbedah-bedah",
      price: "25.5",
      image_title: "Noken",
      image: "https://baktinews.bakti.or.id/sites/default/files/images/noken.jpg",
    },
    {
      id: "434",
      name: "Gelang",
      description: "Gelang  tradisional papua, gelang ini sangat unik karena dibuat dengan bahan yang alami dari tali tumbuh-tumbuhan",
      price: "5.66",
      image_title: "Gelang Tangan",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Gelang_Anyaman.jpg/220px-Gelang_Anyaman.jpg",
    },
    {
      id: "435",
      name: "Kalung",
      description: "Kalung  tradisional papua, kalung ini sangat unik karena dibuat dengan bahan yang alami dari tali tumbuh-tumbuhan",
      price: "70",
      image_title: "Kalung",
      image: "https://images.tokopedia.net/img/cache/250-square/VqbcmM/2022/2/15/b93299e1-4f30-4378-96be-1c6acbc92ecd.png?ect=4g",
    },
  ],
};
var app = new Vue({
  el: "#app",
  data: data,
});
